opsobot {
  credentials {
#     token = "50odCBxP9sJFkm8ZpQiL_0MP3S1YFc5cwRtvJ4qZa13"
    token = "Tb6l77W6dQZn_wpEm8k4FGYSdtBFr2no9V8ALOOguU5"
    user_id = "PHP5o4Aq7XDmDMMhq"
    avatar = "https://avatars.slack-edge.com/2020-08-07/1281096213222_ad3d6fc601b6e272eb7e_512.png"
  }
  environment {
    host = "https://chat.czk.comarch.com"
#     room_id = "CESJrJsPqoDEB67mC" #prod
    room_id = "mj2b2pds8Laht8nac" #test
  }
}

akka.quartz {
  defaultTimezone = "GMT+2"
  schedules {
    MondaysAndWednesdays {
#       expression = "0 0 11 ? * MON,TUE,WED,THU,FRI *"
        expression = "*/30 * * ? * *" #testSchedule
      description = "Next year"
    }
    PizzaDays {
      expression = "0 0 0 1 1 ? 2200"
      description = "With +15 sec interval from now"
    }
  }
}
