akka {
  quartz {
    defaultTimezone = "GMT+2"
    schedules {
      MondaysAndWednesdays {
        expression = "0 0 11 ? * MON,WED"
        description = "Send menu every Monday and Wednesday at 11:00 CEST"
      }
      PizzaDays {
        expression = "0 0 10 ? * TUE,THU,FRI"
        description = "Send menu every pizza day at 10:00 CEST"
      }
      Every10Seconds {
        expression = "0/10 * * ? * *"
      }
      Every10Seconds2 {
        expression = "4/10 * * ? * *"
      }
    }
  }
}