include "schedules.conf"

opsobot {
  credentials {
    token = "50odCBxP9sJFkm8ZpQiL_0MP3S1YFc5cwRtvJ4qZa13"
    user_id = "PHP5o4Aq7XDmDMMhq"
    avatar = "https://avatars.slack-edge.com/2020-08-07/1281096213222_ad3d6fc601b6e272eb7e_512.png"
  }
  environment {
    host = "https://chat.czk.comarch.com"
    //    room_id = "ocGiwg5SsYpQ7nBL2"
    room_id = "mj2b2pds8Laht8nac"
  }
}

akka.quartz.schedules {
  MondaysAndWednesdays {
    expression = "0/10 * * ? * *"
    description = "Every 10 seconds, starts at 0 seconds"
  }
  PizzaDays {
    expression = "5/10 * * ? * *"
    description = "Every 10 seconds, starts at 5 seconds"
  }
}

